#!/usr/bin/env python3
"""Generate docs/rules/P*.md from the rule catalog.

The mechanical half of each page -- id, title, group, verdict, weight, patterns,
fix, source -- is read from rules/anti-patterns.yaml, so a page cannot drift from
the catalog it documents. The judgement half -- intent, known false-positive
modes, what the escape hatches mean -- is authored in docs/rules/_annotations.yaml.

Usage:
    python scripts/gen_rule_docs.py            # write the pages
    python scripts/gen_rule_docs.py --check    # fail if any page is stale
    python scripts/gen_rule_docs.py --list     # print the page paths only

Exit code 0 = in sync, 1 = drift, 2 = could not run.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    print("gen_rule_docs: PyYAML is required (pip install pyyaml)", file=sys.stderr)
    sys.exit(2)

REPO_ROOT = Path(__file__).resolve().parent.parent
CATALOG = REPO_ROOT / "rules" / "anti-patterns.yaml"
ANNOTATIONS = REPO_ROOT / "docs" / "rules" / "_annotations.yaml"
OUT_DIR = REPO_ROOT / "docs" / "rules"

GROUP_TITLES = {
    "A": "A - the impact does not exist",
    "B": "B - the precondition is unreachable or disallowed",
    "C": "C - the harm is bounded or unprofitable",
    "D": "D - already known",
    "E": "E - the bug is fine; the report fails",
}

VERDICT_MEANING = {
    "hard": "hard fail - the verdict becomes KILL",
    "soft": "soft fail - the verdict becomes HOLD",
    "warn": "note only - does not change the verdict",
}

# The tool has never been run against an accepted or paid finding, so the
# false-positive rate does not exist. It is rendered as "unmeasured" on every
# page rather than omitted, because an omitted field reads as "not applicable".
FP_CELL = "**unmeasured** - there is no accepted/paid control set yet. See docs/control-set.md"


def evidence_cell(rule: dict) -> str:
    """How the rule got here: derived from N log rows, or a judgement."""
    rows = rule.get("origin_rows")
    evidence = rule.get("evidence", "unknown")
    if not isinstance(rows, int):
        return "not recorded"
    if evidence == "in_sample" and rows > 0:
        return ("in-sample, derived from " + str(rows) + " log row(s). A derivation count, not a "
                "detection rate")
    if rows == 0 and evidence == "none":
        return "no supporting log rows - a judgement, not a measurement"
    return "in-sample, " + str(rows) + " log row(s), evidence=" + str(evidence)


REQUIRED_ANNOTATION_KEYS = (
    "intent",
    "signals_note",
    "escape_hatches",
    "false_positives",
    "examples",
    "changelog",
)


def load_catalog() -> tuple[list[dict], str]:
    doc = yaml.safe_load(CATALOG.read_text(encoding="utf-8"))
    return doc["rules"], str(doc.get("version", ""))


def load_annotations() -> dict:
    doc = yaml.safe_load(ANNOTATIONS.read_text(encoding="utf-8"))
    return doc["rules"]


def check_annotations(rules: list[dict], notes: dict) -> list[str]:
    problems: list[str] = []
    catalog_ids = [r["id"] for r in rules]
    if len(catalog_ids) != len(set(catalog_ids)):
        problems.append("rules/anti-patterns.yaml contains duplicate rule ids")
    for rid in catalog_ids:
        if rid not in notes:
            problems.append("docs/rules/_annotations.yaml has no entry for " + rid)
            continue
        entry = notes[rid]
        for key in REQUIRED_ANNOTATION_KEYS:
            if key not in entry:
                problems.append("_annotations.yaml: " + rid + " is missing " + key)
        examples = entry.get("examples") or {}
        for key in ("fires", "does_not_fire"):
            if not (examples.get(key) or "").strip():
                problems.append("_annotations.yaml: " + rid + " examples." + key + " is empty")
        if not entry.get("false_positives"):
            problems.append("_annotations.yaml: " + rid + " lists no false-positive modes")
        for entry_changelog in entry.get("changelog") or []:
            if not entry_changelog.get("date") or not entry_changelog.get("note"):
                problems.append("_annotations.yaml: " + rid + " changelog entry missing date or note")
    for rid in sorted(set(notes) - set(catalog_ids)):
        problems.append("_annotations.yaml: " + rid + " is not in the catalog (stale annotation)")
    return problems


def fence_patterns(patterns: list[str]) -> str:
    return "\n".join("  " + p for p in patterns)


def render_rule(rule: dict, note: dict, catalog_version: str) -> str:
    rid = rule["id"]
    out: list[str] = []
    out.append("# " + rid + " - " + rule["title"])
    out.append("")
    out.append("<!-- Generated by scripts/gen_rule_docs.py. Do not edit by hand. -->")
    out.append("<!-- Mechanical fields come from rules/anti-patterns.yaml (catalog version " + catalog_version + "). -->")
    out.append("<!-- Judgement fields come from docs/rules/_annotations.yaml. -->")
    out.append("")
    out.append("| | |")
    out.append("|---|---|")
    out.append("| **Group** | " + GROUP_TITLES.get(rule["group"], rule["group"]) + " |")
    out.append("| **Verdict** | `{v}` - {m} |".replace("{v}", rule["verdict"]).replace("{m}", VERDICT_MEANING.get(rule["verdict"], "unknown")))
    out.append("| **Weight** | " + str(rule["weight"]) + " of 100 |")
    out.append("| **Source** | `doc: docs/rules/" + rid + ".md` |")
    out.append("| **Evidence** | " + evidence_cell(rule) + " |")
    out.append("| **False-positive rate** | " + FP_CELL + " |")
    out.append("| **Last validated** | " + str(rule.get("last_validated", "not recorded")) + " |")
    out.append("")
    out.append("## Intent")
    out.append("")
    out.append(" ".join(str(note["intent"]).split()))
    out.append("")
    out.append("## Detection signals")
    out.append("")
    out.append(" ".join(str(note["signals_note"]).split()))
    out.append("")
    out.append("Patterns are case-insensitive regular expressions matched against the full text of the")
    out.append("draft finding, subject to the engine rules below.")
    out.append("")
    if rule.get("structural"):
        out.append("**Structural, not a pattern match.** This rule dispatches to a hand-written")
        out.append("matcher (`" + str(rule["structural"]) + "`), because the condition is a relationship")
        out.append("between parts of the report rather than a phrase in it. There is no pattern to")
        out.append("quote; the description above is the specification.")
        out.append("")
    if rule.get("any_of"):
        out.append("**Fires when at least one of these matches:**")
        out.append("")
        out.append("```text")
        out.append(fence_patterns(rule["any_of"]))
        out.append("```")
        out.append("")
    if rule.get("all_of"):
        out.append("**And all of these also match:**")
        out.append("")
        out.append("```text")
        out.append(fence_patterns(rule["all_of"]))
        out.append("```")
        out.append("")
    if not rule.get("any_of") and not rule.get("all_of") and not rule.get("structural"):
        out.append("_No mechanical signal: this rule is doctrine, applied by the reader._")
        out.append("")
    if rule.get("escalate_on"):
        out.append("**Escalates.** A match on any of these strong forms raises the rule to `"
                   + str(rule.get("escalate_to", "hard")) + "`, because these are the forms that name the")
        out.append("problem rather than hedge around it:")
        out.append("")
        out.append("```text")
        out.append(fence_patterns(rule["escalate_on"]))
        out.append("```")
        out.append("")
    if rule.get("downgrade_on"):
        out.append("**Dropped.** A match on any of these is discarded outright, so the rule does not fire")
        out.append("at all. This is how the rule stops firing on ordinary scaffolding:")
        out.append("")
        out.append("```text")
        out.append(fence_patterns(rule["downgrade_on"]))
        out.append("```")
        out.append("")
    if rule.get("negation_aware") is False:
        out.append("**Not negation-aware.** The engine does not apply its negation window to this rule.")
        out.append("")
    if rule.get("ignore_sections"):
        out.append("**Skipped sections:** " + ", ".join("`" + s + "`" for s in rule["ignore_sections"])
                   + ". A match inside one of these is not the finding's claim.")
        out.append("")
    out.append("## Escape hatches")
    out.append("")
    out.append(" ".join(str(note["escape_hatches"]).split()))
    out.append("")
    if rule.get("none_of"):
        scope = rule.get("none_of_scope", "document")
        if scope == "sentence":
            out.append("**Suppressed when any of these matches, in the same sentence as the fire:**")
        else:
            out.append("**Suppressed when any of these matches anywhere in the finding:**")
        out.append("")
        out.append("```text")
        out.append(fence_patterns(rule["none_of"]))
        out.append("```")
        out.append("")
    out.append("## Known false-positive modes")
    out.append("")
    out.append("These are the shapes where the rule fires on something it should not. They are the")
    out.append("reason a firing is a prompt to check, not a verdict.")
    out.append("")
    for item in note["false_positives"]:
        out.append("- " + " ".join(str(item).split()))
    out.append("")
    out.append("## Synthetic examples")
    out.append("")
    out.append("Both examples are synthetic. They describe no real report and no real target.")
    out.append("")
    fires = " ".join(str(note["examples"]["fires"]).split())
    quiet = " ".join(str(note["examples"]["does_not_fire"]).split())
    out.append("**Fires:** " + fires)
    out.append("")
    out.append("**Does not fire:** " + quiet)
    out.append("")
    out.append("## Corrective action")
    out.append("")
    out.append(" ".join(str(rule["fix"]).split()))
    out.append("")
    out.append("## Changelog")
    out.append("")
    out.append("| Date | Change |")
    out.append("|---|---|")
    for entry in note["changelog"]:
        out.append("| " + str(entry["date"]) + " | " + " ".join(str(entry["note"]).split()) + " |")
    out.append("")
    out.append("---")
    out.append("")
    out.append("[Back to the catalog index](README.md)")
    out.append("")
    return "\n".join(out)


def render_index(rules: list[dict], catalog_version: str) -> str:
    out: list[str] = []
    out.append("# Anti-pattern catalog")
    out.append("")
    out.append("<!-- Generated by scripts/gen_rule_docs.py. Do not edit by hand. -->")
    out.append("")
    out.append("One page per rule. " + str(len(rules)) + " rules, `"
               + rules[0]["id"] + "`-`" + rules[-1]["id"] + "`, catalog version "
               + catalog_version + ". The catalog itself is")
    out.append("[`rules/anti-patterns.yaml`](../../rules/anti-patterns.yaml) and it is the authority;")
    out.append("these pages are generated from it and cannot drift from it.")
    out.append("")
    out.append("| ID | Title | Group | Verdict | Weight |")
    out.append("|---|---|---|---|---:|")
    for rule in rules:
        out.append("| [`{i}`]({i}.md) | {t} | {g} | `{v}` | {w} |".format(
            i=rule["id"], t=rule["title"], g=rule["group"], v=rule["verdict"], w=rule["weight"]))
    out.append("")
    out.append("## How to read a page")
    out.append("")
    out.append("| Section | What it is |")
    out.append("|---|---|")
    out.append("| Intent | What the anti-pattern is |")
    out.append("| Detection signals | What the regexes look for, and what they miss |")
    out.append("| Escape hatches | The `none_of` patterns that suppress the rule, and why |")
    out.append("| Known false-positive modes | Where the rule fires on something it should not |")
    out.append("| Synthetic examples | One firing case and one quiet case |")
    out.append("| Corrective action | The `fix` string the tool prints |")
    out.append("| Changelog | When the rule changed and why |")
    out.append("")
    out.append("## Two things the generated pages reveal on purpose")
    out.append("")
    out.append("1. **The patterns are public.** The catalog is embedded in the binary, so hiding the")
    out.append("   regexes would hide nothing. What is *not* public is any target: no page, pattern or")
    out.append("   example names a program, a chain or a repository.")
    out.append("2. **The pages carry ecosystem tokens; the catalog does not.** A pattern that matches an")
    out.append("   ecosystem's test marker is shown here verbatim, because a rule page that cannot say")
    out.append("   what it matches is useless. The *balanced pack set* in")
    out.append("   [`rules/packs/`](../../rules/packs/) is what keeps that from being a statement")
    out.append("   about the author - see [`docs/tripwires.md`](../tripwires.md).")
    out.append("")
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail if a page is missing or stale")
    parser.add_argument("--list", action="store_true", help="print the page paths and exit")
    args = parser.parse_args(argv)

    rules, catalog_version = load_catalog()
    notes = load_annotations()

    problems = check_annotations(rules, notes)
    if problems:
        print("gen_rule_docs: annotations are incomplete", file=sys.stderr)
        for p in problems:
            print("  " + p, file=sys.stderr)
        return 2

    rendered = {OUT_DIR / (r["id"] + ".md"): render_rule(r, notes[r["id"]], catalog_version) for r in rules}
    rendered[OUT_DIR / "README.md"] = render_index(rules, catalog_version)

    if args.list:
        for path in sorted(rendered):
            print(path.relative_to(REPO_ROOT).as_posix())
        return 0

    if args.check:
        stale: list[str] = []
        for path, text in sorted(rendered.items()):
            rel = path.relative_to(REPO_ROOT).as_posix()
            if not path.exists():
                stale.append(rel + ": missing")
                continue
            if path.read_text(encoding="utf-8") != text:
                stale.append(rel + ": out of date")
        expected = {p.name for p in rendered}
        for existing in sorted(OUT_DIR.glob("P*.md")):
            if existing.name not in expected:
                stale.append(existing.relative_to(REPO_ROOT).as_posix() + ": no such rule in the catalog")
        if stale:
            print("gen_rule_docs --check: generated pages are stale", file=sys.stderr)
            for s in stale:
                print("  " + s, file=sys.stderr)
            print("", file=sys.stderr)
            print("Run: python scripts/gen_rule_docs.py", file=sys.stderr)
            return 1
        print("gen_rule_docs --check: " + str(len(rendered)) + " page(s) in sync with the catalog")
        return 0

    changed = 0
    for path, text in sorted(rendered.items()):
        old = path.read_text(encoding="utf-8") if path.exists() else None
        if old != text:
            path.write_text(text, encoding="utf-8", newline="\n")
            changed += 1
    print("gen_rule_docs: wrote " + str(len(rendered)) + " page(s), " + str(changed) + " changed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
